[project]
name = "cli_exit_tools"
version = "0.1.0"  # or import from __init__conf__ dynamically
description = "CLI and exit tools with clean signal handling"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["click>=8.1"]

[project.scripts]
cli_exit_tools = "cli_exit_tools.cli:main"

[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/cli_exit_tools"]

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.pyright]
typeCheckingMode = "strict"
