[project]
name = "lib_cli_exit_tools"
version = "0.1.0"
description = "CLI exit handling helpers: clean signals, exit codes, and error printing"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["click>=8.1"]
license = { text = "MIT" }
authors = [{ name = "Robert Nowotny", email = "bitranox@gmail.com" }]
keywords = ["cli", "exit", "signals", "errors", "click"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "License :: OSI Approved :: MIT License",
  "Environment :: Console",
  "Operating System :: OS Independent",
  "Typing :: Typed",
]

[project.urls]
Homepage = "https://github.com/bitranox/lib_cli_exit_tools"
Repository = "https://github.com/bitranox/lib_cli_exit_tools.git"
Issues = "https://github.com/bitranox/lib_cli_exit_tools/issues"

[project.optional-dependencies]
dev = [
  "pytest>=8.2",
  "pytest-cov>=5.0",
  "ruff>=0.5",
  "pyright>=1.1",
  "build>=1.2",
  "twine>=5.1",
  "codecov>=2.1.13",
]

[project.scripts]
lib_cli_exit_tools = "lib_cli_exit_tools.cli:main"
# Friendly alias (optional):
cli-exit-tools = "lib_cli_exit_tools.cli:main"
lib-cli-exit-tools = "lib_cli_exit_tools.cli:main"

[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"



[tool.hatch.build.targets.wheel]
packages = ["src/lib_cli_exit_tools"]
include = ["src/lib_cli_exit_tools/py.typed"]

[tool.ruff]
line-length = 160
target-version = "py313"

[tool.pyright]
typeCheckingMode = "strict"

[tool.coverage.run]
branch = true
parallel = false
data_file = ".coverage.unit"
source = ["src/lib_cli_exit_tools"]

[tool.coverage.report]
omit = [
  "tests/*",
  "packaging/*",
  "src/lib_cli_exit_tools/__init__conf__.py",
]
fail_under = 85
show_missing = true
