name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Tests (Python ${{ matrix.python }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install make on Windows
        if: runner.os == 'Windows'
        run: choco install make
      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run full test suite (lint, types, tests, coverage, codecov)
        run: make test
      - name: Build wheel/sdist
        run: python -m build
      - name: Verify wheel install in clean env
        run: |
          python -m venv .venv_wheel
          . .venv_wheel/bin/activate 2>/dev/null || .venv_wheel\Scripts\activate
          pip install dist/*.whl
          lib_cli_exit_tools --version || python -m lib_cli_exit_tools --version

  pipx-uv:
    name: pipx/uv verification (ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Build wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build
      - name: pipx install from wheel
        run: |
          python -m pip install pipx
          pipx install dist/*.whl
          lib_cli_exit_tools --version
      - name: uv tool install
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$HOME/.local/share/uv/bin:$PATH"
          uv tool install .
          lib_cli_exit_tools --version

  # nix and conda packaging builds are disabled for now to keep CI green.
