name: Release

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Verify PyPI token is set
        run: |
          if [ -z "${{ secrets.PYPI_API_TOKEN }}" ]; then
            echo "::error title=Missing PyPI token::Set the PYPI_API_TOKEN secret in GitHub repository settings to enable PyPI publishing on releases." 
            echo "See: https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions" 
            exit 1
          fi
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build artifacts
        run: |
          python -m pip install --upgrade pip build
          python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
